/** 
 * APS SDK
 *
 * The APS Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Model Derivative
 * Use the Model Derivative API to translate designs from one CAD format to another. You can also use this API to extract metadata from a model.
 *
 * Contact: aps.help@autodesk.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.autodesk.aps.modelderivative.model;  
  
 /**
  * Represents optional parameters for the `getAllProperties` method.
  * This class uses the Builder pattern to allow flexible construction of objects.
  */
public class GetAllPropertiesOptionalParams{
    private String acceptEncoding;    
    private Boolean xAdsForce;    
    private XAdsDerivativeFormat xAdsDerivativeFormat;    
    private Region region;    
    private Integer objectid;    
    private String forceget;    
    private String accessToken;

    private GetAllPropertiesOptionalParams(Builder builder){
        this.acceptEncoding = builder.acceptEncoding;    
this.xAdsForce = builder.xAdsForce;    
this.xAdsDerivativeFormat = builder.xAdsDerivativeFormat;    
this.region = builder.region;    
this.objectid = builder.objectid;    
this.forceget = builder.forceget;    
        this.accessToken = builder.accessToken;
    }

    
    /**
     * Builder class for constructing instances of GetAllPropertiesOptionalParams.
     */
    public static class Builder {
         private String acceptEncoding;    
 private Boolean xAdsForce;    
 private XAdsDerivativeFormat xAdsDerivativeFormat;    
 private Region region;    
 private Integer objectid;    
 private String forceget;    
        private String accessToken;      
        /**
         * @param acceptEncoding A comma separated list of the algorithms you want the response to be encoded in, specified in the order of preference.  
 * 
 * If you specify &#x60;&#x60;gzip&#x60;&#x60; or &#x60;&#x60;*&#x60;&#x60;, content is compressed and returned in gzip format.
 * 
         *
         * @return The Builder instance for chaining.
         */
        public Builder acceptEncoding(String acceptEncoding){
            this.acceptEncoding = acceptEncoding;
            return this;
        }     
        /**
         * @param xAdsForce - &#x60;&#x60;true&#x60;&#x60;: Forces the system to parse property data all over again. Use this option to retrieve an object tree when previous attempts have failed.
 * - &#x60;&#x60;false&#x60;&#x60;: (Default) Use previously parsed property data to extract the object tree.
 * 
         *
         * @return The Builder instance for chaining.
         */
        public Builder xAdsForce(Boolean xAdsForce){
            this.xAdsForce = xAdsForce;
            return this;
        }     
        /**
         * @param xAdsDerivativeFormat Specifies what Object IDs to return, if the design has legacy SVF derivatives generated by the BIM Docs service. Possible values are:  
 * 
 * - &#x60;&#x60;latest&#x60;&#x60; - (Default) Return SVF2 Object IDs. 
 * - &#x60;&#x60;fallback&#x60;&#x60; - Return SVF Object IDs.  
 * 
 * **Note:**  
 * 
 * 1. This parameter applies only to designs with legacy SVF derivatives generated by the BIM 360 Docs service. 
 * 2. The BIM 360 Docs service now generates SVF2 derivatives. SVF2 Object IDs may not be compatible with the SVF Object IDs previously generated by the BIM 360 Docs service. Setting this header to fallback may resolve backward compatibility issues resulting from Object IDs of legacy SVF derivatives being retained on the client side. 
 * 3. If you use this parameter with one derivative (URN), you must use it consistently across the following: 
 * 
 *    - &#x60;Create Translation Job &lt;/en/docs/model-derivative/v2/reference/http/job-POST&gt;&#x60;_ (for OBJ output) 
 *    - &#x60;Fetch Object Tree &lt;/en/docs/model-derivative/v2/reference/http/urn-metadata-modelguid-GET&gt;&#x60;_
 *    - &#x60;Fetch All Properties &lt;/en/docs/model-derivative/v2/reference/http/urn-metadata-guid-properties-GET&gt;&#x60;_
 *    - &#x60;Fetch Specific Properties &lt;en/docs/model-derivative/v2/reference/http/metadata/urn-metadata-guid-properties-query-POST&gt;&#x60;_
 * 
         *
         * @return The Builder instance for chaining.
         */
        public Builder xAdsDerivativeFormat(XAdsDerivativeFormat xAdsDerivativeFormat){
            this.xAdsDerivativeFormat = xAdsDerivativeFormat;
            return this;
        }     
        /**
         * @param region Specifies the data center where the manifest and derivatives of the specified source design are stored. Possible values are:
 * 
 * - &#x60;&#x60;US&#x60;&#x60; - (Default) Data center for the US region.
 * - &#x60;&#x60;EMEA&#x60;&#x60; - Data center for the European Union, Middle East, and Africa. 
 * - &#x60;&#x60;AUS&#x60;&#x60; - Data center for the Australia region.
 * - &#x60;&#x60;CAN&#x60;&#x60; - Data center for the Canada region.
 * - &#x60;&#x60;DEU&#x60;&#x60; - Data center for the Germany region.
 * - &#x60;&#x60;IND&#x60;&#x60; - Data center for the India region.
 * - &#x60;&#x60;JPN&#x60;&#x60; - Data center for the Japan region.
 * - &#x60;&#x60;GBR&#x60;&#x60;  - Data center for the United Kingdom region.
 * 
         *
         * @return The Builder instance for chaining.
         */
        public Builder region(Region region){
            this.region = region;
            return this;
        }     
        /**
         * @param objectid The Object ID of the object you want to restrict the response to. If you do not specify this parameter, all properties of all objects within the Model View are returned.  
         *
         * @return The Builder instance for chaining.
         */
        public Builder objectid(Integer objectid){
            this.objectid = objectid;
            return this;
        }     
        /**
         * @param forceget &#x60;&#x60;true&#x60;&#x60;: Retrieves large resources, even beyond the 20 MB limit. If exceptionally large (over 800 MB), the system acts as if &#x60;&#x60;forceget&#x60;&#x60; is &#x60;&#x60;false&#x60;&#x60;. 
 * 
 * &#x60;&#x60;false&#x60;&#x60;: (Default) Does not retrieve resources if they are larger than 20 MB.
 * 
         *
         * @return The Builder instance for chaining.
         */
        public Builder forceget(String forceget){
            this.forceget = forceget;
            return this;
        }     
        /**
         * @param accessToken The access token string.
         *
         * @return The Builder instance for chaining.
         */
         public Builder accessToken(String accessToken) {
            this.accessToken = accessToken;
            return this;
        }
        /**
         * Builds and returns an instance of GetAllPropertiesOptionalParams.
         * 
         * @return GetAllPropertiesOptionalParams object.
         */
        public GetAllPropertiesOptionalParams build() {
            return new GetAllPropertiesOptionalParams(this);
        }
    }

    // Getters for each field
    /**
     * Gets the acceptEncoding value.
     *
     * @return String
     */
    public String getAcceptEncoding(){
        return acceptEncoding;
    }
    /**
     * Gets the xAdsForce value.
     *
     * @return Boolean
     */
    public Boolean getXAdsForce(){
        return xAdsForce;
    }
    /**
     * Gets the xAdsDerivativeFormat value.
     *
     * @return XAdsDerivativeFormat
     */
    public XAdsDerivativeFormat getXAdsDerivativeFormat(){
        return xAdsDerivativeFormat;
    }
    /**
     * Gets the region value.
     *
     * @return Region
     */
    public Region getRegion(){
        return region;
    }
    /**
     * Gets the objectid value.
     *
     * @return Integer
     */
    public Integer getObjectid(){
        return objectid;
    }
    /**
     * Gets the forceget value.
     *
     * @return String
     */
    public String getForceget(){
        return forceget;
    }
     /**
     * Gets the access token for authentication.
     *
     * @return String.
     */
     public String getAccessToken() {
        return accessToken;
    }
    /**
     * Sets the access token for authentication.
     * 
     * @param accessToken The access token string.
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
}  
